# Construcción, ajuste y evaluación de Modelos de Machine Learning

Tarea: Construir, ajustar y evaluar modelos de Machine Learning utilizando técnicas y algoritmos apropiados.

Instrucciones:

* Seleccionar algoritmos de Machine Learning adecuados para resolver el problema planteado.
* Entrenar los modelos utilizando los datos preprocesados.
* Realizar ajustes de hiperparámetros para optimizar el rendimiento del modelo.
* Evaluar los modelos utilizando métricas de rendimiento específicas.

Importancia: Esta etapa es fundamental para desarrollar modelos precisos y eficientes que puedan resolver problemas específicos de manera efectiva

Empezamos probando con un módelo básico de Random Forest Classifier

In [1]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np
import pandas as pd


In [2]:
data_df = pd.read_csv("../../data/processed/TCGA_GBM_LGG_Mutations_clean.csv") #change path when testing
data_df.sample(5)


Grade  Gender  Age_at_diagnosis  Race  Tumor_Type  Tumor_Specification   
472      0       1             47.45     4           0                    1  \
80       0       0             30.93     1           0                    1   
544      1       0             63.91     1           3                    0   
774      1       1             67.02     1           3                    0   
787      1       1             30.90     3           3                    0   

     IDH1  TP53  ATRX  PTEN  ...  FUBP1  RB1  NOTCH1  BCOR  CSMD3  SMARCA4   
472     0     0     0     0  ...      0    0       0     0      0        0  \
80      1     0     0     0  ...      0    0       1     0      0        0   
544     0     0     0     1  ...      0    0       0     0      0        0   
774     0     0     0     0  ...      0    0       0     0      0        0   
787     1     1     1     0  ...      0    0       0     0      0        0   

     GRIN2A  IDH2  FAT4  PDGFRA  
472       0     0     0       0  
80        0     0     0       0  
544       0     0     0       0  
774       0     0     0       0  
787       0     0     0       0  

[5 rows x 26 columns]

In [3]:
X=data_df.drop(["Grade"], axis=1)
y=data_df["Grade"]
y.sample(5)

776    1
487    0
471    0
822    1
452    0
Name: Grade, dtype: int64

Separamos nuestros datos para probar y entrenar con train_test_split y generamos el fit para el modelo

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=44)
rf_model = RandomForestClassifier(n_estimators=50, random_state=44)
rf_model.fit(X_train,y_train)

RandomForestClassifier(n_estimators=50, random_state=44)

Aquí podemos ya ver como el módelo predice el grado con base a su entrenamiento.

In [5]:
predictions = rf_model.predict(X_test)
predictions

array([0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0], dtype=int64)

In [6]:
rf_model.predict_proba(X_test)

array([[1.  , 0.  ],
       [0.98, 0.02],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.96, 0.04],
       [1.  , 0.  ],
       [0.1 , 0.9 ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.28, 0.72],
       [0.98, 0.02],
       [0.04, 0.96],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.98, 0.02],
       [0.98, 0.02],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.98, 0.02],
       [0.  , 1.  ],
       [0.78, 0.22],
       [0.  , 1.  ],
       [0.02, 0.98],
       [1.  , 0.  ],
       [0.9 , 0.1 ],
       [0.92, 0.08],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.96, 0.04],
       [0.98, 0.02],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.96, 0.04],
       [0.94, 0.06],
       [0.98, 0.02],
       [0.02, 0.98],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.98, 0.02],
       [0.  , 1.  ],
       [0.98, 0.02],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.  ,

De igual forma, podemos ver que propiedad de nuestros datos es la más importante para el proceso de predicción

In [7]:
importances = rf_model.feature_importances_
columns = X.columns
i=0
while i < len(columns):
    print(f" The importance of feature '{columns[i]}' is {round(importances[i] * 100, 2)}%.")
    i += 1

 The importance of feature 'Gender' is 0.22%.
 The importance of feature 'Age_at_diagnosis' is 7.03%.
 The importance of feature 'Race' is 0.5%.
 The importance of feature 'Tumor_Type' is 42.32%.
 The importance of feature 'Tumor_Specification' is 20.93%.
 The importance of feature 'IDH1' is 17.95%.
 The importance of feature 'TP53' is 0.71%.
 The importance of feature 'ATRX' is 1.87%.
 The importance of feature 'PTEN' is 1.79%.
 The importance of feature 'EGFR' is 1.13%.
 The importance of feature 'CIC' is 2.43%.
 The importance of feature 'MUC16' is 0.24%.
 The importance of feature 'PIK3CA' is 0.06%.
 The importance of feature 'NF1' is 0.15%.
 The importance of feature 'PIK3R1' is 0.1%.
 The importance of feature 'FUBP1' is 0.67%.
 The importance of feature 'RB1' is 0.37%.
 The importance of feature 'NOTCH1' is 0.39%.
 The importance of feature 'BCOR' is 0.13%.
 The importance of feature 'CSMD3' is 0.02%.
 The importance of feature 'SMARCA4' is 0.17%.
 The importance of feature 'GRI

El modelo de Random Forest nos arrojo una precisión de 100, sin embargo esto se debe al overfitting por nuestro tipo de datos. Por lo que para nuestro modelo usaremos una regresión linear en vez del Ranom Forest

In [8]:
from sklearn.metrics import classification_report
y_true, y_pred = y_test, rf_model.predict(X_test)
print(classification_report(y_true, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       150
           1       1.00      1.00      1.00       108

    accuracy                           1.00       258
   macro avg       1.00      1.00      1.00       258
weighted avg       1.00      1.00      1.00       258



In [9]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
clf = RandomForestClassifier(n_estimators=50, random_state=44)
param_grid = {
    'n_estimators': [5, 10, 15, 20],
    'max_depth': [2, 5, 7, 9]
}
grid_clf = GridSearchCV(clf, param_grid, cv=10)
grid_clf.fit(X_train, y_train)

GridSearchCV(cv=10,
             estimator=RandomForestClassifier(n_estimators=50, random_state=44),
             param_grid={'max_depth': [2, 5, 7, 9],
                         'n_estimators': [5, 10, 15, 20]})

In [10]:
grid_clf.cv_results_

{'mean_fit_time': array([0.0040997 , 0.0069993 , 0.00940051, 0.01189909, 0.00429876,
        0.00740104, 0.010199  , 0.01409943, 0.00459936, 0.00769978,
        0.01169949, 0.01299961, 0.00412345, 0.00730002, 0.01130047,
        0.01439941]),
 'std_fit_time': array([0.00083095, 0.00089399, 0.00079971, 0.00030046, 0.00045718,
        0.00048931, 0.00059981, 0.00083038, 0.0004898 , 0.00045839,
        0.00184641, 0.00044816, 0.00053977, 0.00045828, 0.00078054,
        0.00048978]),
 'mean_score_time': array([0.00140038, 0.00140033, 0.00180008, 0.00130074, 0.00110197,
        0.00129867, 0.00140159, 0.00150058, 0.00100067, 0.00120022,
        0.00150118, 0.00149903, 0.00099819, 0.00139997, 0.00139892,
        0.00160058]),
 'std_score_time': array([6.63312883e-04, 4.89658343e-04, 4.00078516e-04, 4.58054538e-04,
        2.99564211e-04, 4.59354240e-04, 4.90139243e-04, 4.99987709e-04,
        6.16670473e-07, 3.99816163e-04, 9.21708621e-04, 5.00873825e-04,
        4.07137684e-06, 4.89950417e-

In [11]:

def evaluate_model(y_true, y_pred):
    # Calcular la matriz de confusión
    conf_matrix = confusion_matrix(y_true, y_pred)
    print("Confusion Matrix:")
    print(conf_matrix)
    
    # Calcular el reporte de clasificación
    class_report = classification_report(y_true, y_pred)
    print("Classification Report:")
    print(class_report)

# Evaluar el modelo con los datos de prueba
evaluate_model(y_test, predictions)

# El modelo presenta overfitting debido al reduccido tamaño del dataset

Confusion Matrix:
[[150   0]
 [  0 108]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       150
           1       1.00      1.00      1.00       108

    accuracy                           1.00       258
   macro avg       1.00      1.00      1.00       258
weighted avg       1.00      1.00      1.00       258

